#ifndef CONFIGS_H
#define CONFIGS_H

#define ITERATIONS_PER_SECOND 1000

#define MIN_SIMULATION_SPEED 0.01
#define DEFAULT_SIMULATION_SPEED 1
#define MAX_SIMULATION_SPEED 10

#define TIME_TO_SLEEP 10000

#define SCREEN_SIZE_X 1920
#define SCREEN_SIZE_Y 1080
#define GRAVITATIONAL_CONSTATNT_MPS -9.84

#define COLLISION_EPSILON 1e-6
#define MINIMUM_OBJECT_DISTANCE 1e-6
// #define ENABLE_LOGGING

#define psize_t double

#endif // CONFIGS_H