#ifndef CONFIGS_H
#define CONFIGS_H

#define ITERATIONS_PER_SECOND 1000
#define DEFAULT_SIMULATION_SPEED 0.001

#define MIN_SIMULATION_SPEED 0.001
#define MAX_SIMULATION_SPEED 5

#define MINIMUM_SLEEP_TIME 5 // Minimum time to sleep allowed in micro seconds

#define SCREEN_SIZE_X 1920
#define SCREEN_SIZE_Y 1080
#define GRAVITATIONAL_CONSTATNT_MPS -9.84

#define COLLISION_EPSILON 1e-6
#define MINIMUM_OBJECT_DISTANCE 1e-6
#define ENABLE_LOGGING

#endif // CONFIGS_H